# Generated by Django 5.1.3 on 2024-11-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
