# Generated by Django 5.1.3 on 2024-11-23 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria'),
        ),
    ]
