# Generated by Django 5.1.3 on 2024-11-25 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
